package main

import (
	"flag"
	"fmt"
)

var (
	command     = flag.String("command", "", "Commande à exécuter: download, download-source, mirror")
	packageName = flag.String("package", "", "Nom du paquet")
	version     = flag.String("version", "", "Version du paquet")
	destDir     = flag.String("dest", "./downloads", "Répertoire de destination")
	origOnly    = flag.Bool("orig-only", false, "Télécharger uniquement le tarball original (pour les paquets sources)")
	silent      = flag.Bool("silent", false, "Mode silencieux sans affichage de progression")
	help        = flag.Bool("help", false, "Afficher l'aide")

	// Mirror-specific flags
	baseURL       = flag.String("url", "http://deb.debian.org/debian", "URL du dépôt à mettre en miroir")
	suites        = flag.String("suites", "bookworm", "Suites à mettre en miroir (séparées par des virgules)")
	components    = flag.String("components", "main", "Composants à mettre en miroir (séparés par des virgules)")
	architectures = flag.String("architectures", "amd64", "Architectures à mettre en miroir (séparées par des virgules)")
	downloadPkgs  = flag.Bool("download-packages", false, "Télécharger les paquets .deb (pas seulement les métadonnées)")
	verbose       = flag.Bool("verbose", false, "Affichage verbeux")
)

func printUsage() {
	fmt.Println("deb-for-all - Outil de gestion des paquets Debian")
	fmt.Println("")
	fmt.Println("Usage:")
	fmt.Println("  deb-for-all -command <commande> [options]")
	fmt.Println("")
	fmt.Println("Commandes:")
	fmt.Println("  download        Télécharger un paquet binaire")
	fmt.Println("  download-source Télécharger un paquet source")
	fmt.Println("  mirror          Créer un miroir d'un dépôt Debian")
	fmt.Println("")
	fmt.Println("Options générales:")
	fmt.Println("  -package <nom>     Nom du paquet")
	fmt.Println("  -version <version> Version du paquet")
	fmt.Println("  -dest <répertoire> Répertoire de destination (défaut: ./downloads)")
	fmt.Println("  -orig-only         Télécharger uniquement le tarball original (paquets sources)")
	fmt.Println("  -silent            Mode silencieux")
	fmt.Println("  -help              Afficher cette aide")
	fmt.Println("")
	fmt.Println("Options pour le miroir:")
	fmt.Println("  -url <URL>               URL du dépôt (défaut: http://deb.debian.org/debian)")
	fmt.Println("  -suites <suites>         Suites séparées par des virgules (défaut: bookworm)")
	fmt.Println("  -components <comps>      Composants séparés par des virgules (défaut: main)")
	fmt.Println("  -architectures <archs>   Architectures séparées par des virgules (défaut: amd64)")
	fmt.Println("  -download-packages       Télécharger les paquets .deb (pas seulement métadonnées)")
	fmt.Println("  -verbose                 Affichage verbeux")
	fmt.Println("")
	fmt.Println("Exemples:")
	fmt.Println("  # Télécharger un paquet binaire")
	fmt.Println("  deb-for-all -command download -package curl")
	fmt.Println("")
	fmt.Println("  # Télécharger une version spécifique d'un paquet binaire")
	fmt.Println("  deb-for-all -command download -package curl -version 7.74.0-1.3+deb11u7")
	fmt.Println("")
	fmt.Println("  # Télécharger un paquet binaire en mode silencieux")
	fmt.Println("  deb-for-all -command download -package hello -dest ./mon-dossier -silent")
	fmt.Println("")
	fmt.Println("  # Télécharger un paquet source")
	fmt.Println("  deb-for-all -command download-source -package hello -version 2.10-2")
	fmt.Println("")
	fmt.Println("  # Créer un miroir des métadonnées seulement")
	fmt.Println("  deb-for-all -command mirror -dest ./debian-mirror -verbose")
	fmt.Println("")
	fmt.Println("  # Créer un miroir complet avec paquets")
	fmt.Println("  deb-for-all -command mirror -dest ./debian-mirror -download-packages -verbose")
	fmt.Println("")
	fmt.Println("  # Miroir personnalisé")
	fmt.Println("  deb-for-all -command mirror -url http://deb.debian.org/debian \\")
	fmt.Println("             -suites bookworm,bullseye -components main,contrib \\")
	fmt.Println("             -architectures amd64,arm64 -dest ./my-mirror")
}
